-- Users table (managed by Supabase Auth, just add roles)
create table profiles (
  id uuid references auth.users primary key,
  name text,
  role text check (role in ('admin', 'doctor', 'staff')),
  created_at timestamp default now()
);

-- Animals table
create table animals (
  id uuid primary key default gen_random_uuid(),
  animal_id text unique, -- autogenerated like SAA-2024-001
  name text,
  species text,
  breed text,
  gender text,
  estimated_age_months int,
  colour text,
  rescue_date date,
  admission_date date,
  rescue_location text,
  current_status text check (current_status in ('critical','moderate','stable','recovered','deceased')),
  category text check (category in ('normal','paralysed','blind','neurological','behavioural','senior','disabled','chemo')),
  lss_incharge text,
  ward text check (ward in ('opd','ipd','inhouse')),
  initial_assessment text,
  is_active boolean default true,
  created_at timestamp default now()
);

-- Animal photos
create table animal_photos (
  id uuid primary key default gen_random_uuid(),
  animal_id uuid references animals(id),
  photo_url text,
  uploaded_at timestamp default now()
);

-- Daily observation logs
create table observation_logs (
  id uuid primary key default gen_random_uuid(),
  animal_id uuid references animals(id),
  log_date date default current_date,
  weight numeric,
  temperature numeric,
  vomiting boolean,
  eating_status text,
  loose_motion boolean,
  food_given text,
  activity_level text,
  additional_notes text,
  reporter text,
  initial_medical_assessment text,
  updated_by uuid references profiles(id),
  created_at timestamp default now()
);

-- Treatment / medication sheet
create table treatment_entries (
  id uuid primary key default gen_random_uuid(),
  animal_id uuid references animals(id),
  drug_name text,
  morning_given boolean default false,
  evening_given boolean default false,
  date date default current_date,
  notes text,
  created_at timestamp default now()
);

-- Monthly stats (editable on dashboard)
create table monthly_stats (
  id uuid primary key default gen_random_uuid(),
  month text, -- e.g. 'April 2024'
  species text, -- 'dog','cat','cow','other'
  admitted int default 0,
  released int default 0,
  deaths int default 0,
  blood_test int default 0,
  xray int default 0,
  surgery int default 0,
  opd int default 0,
  rescue int default 0,
  updated_at timestamp default now()
);

-- Enable Row Level Security on all tables
alter table profiles enable row level security;
alter table animals enable row level security;
alter table animal_photos enable row level security;
alter table observation_logs enable row level security;
alter table treatment_entries enable row level security;
alter table monthly_stats enable row level security;

-- Allow authenticated users to do everything (you can restrict per role later)
create policy "authenticated_all" on profiles for all using (auth.role() = 'authenticated');
create policy "authenticated_all" on animals for all using (auth.role() = 'authenticated');
create policy "authenticated_all" on animal_photos for all using (auth.role() = 'authenticated');
create policy "authenticated_all" on observation_logs for all using (auth.role() = 'authenticated');
create policy "authenticated_all" on treatment_entries for all using (auth.role() = 'authenticated');
create policy "authenticated_all" on monthly_stats for all using (auth.role() = 'authenticated');
